name: Contract Tests

on:
  push:
    branches: [main]

env:
  PACT_BROKER_BASE_URL: ${{ secrets.PACT_BROKER_BASE_URL }}
  PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
  CONSUMER_NAME: ${{ secrets.CONSUMER_NAME }}
  PROVIDER_NAME: ${{ secrets.PROVIDER_NAME }}

jobs:
  publish-contracts:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - run: npm install
      
      - name: 📤 Publish contracts
        env:
          CONSUMER_VERSION: v${{ github.run_number }}
        run: npm run publish:contracts
